import type { Metadata } from "next";
import { MontserratFont } from "@/shared/config/local-font";
import "../shared/styles/global.css";
import "../shared/styles/reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={MontserratFont.className}>{children}</body>
    </html>
  );
}
